name: Flutter Package for MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 build:
   runs-on: macos-latest
   steps:
     - uses: actions/checkout@v2
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
     - run: flutter build macos

     - uses: actions/upload-artifact@v2
       with:
        name: CrossDrop for MacOS
        path: build/macos/Build/Products/Release/*.app